version: "3"

services:
  app:
    build: .
    depends_on:
      - pgsql
    ports:
      - 8772:80
    volumes:
      - .:/var/www/html/app
    links:
      - pgsql
  pgsql:
    image: postgres:12.1
    ports:
      - 8773:7730
    environment:
      - POSTGRES_HOST_AUTH_METHOD=all
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=test
  adminer:
    image: adminer
    restart: always
    depends_on:
      - pgsql
    ports:
      - 8086:8080
    environment:
      - ADMINER_DEFAULT_SERVER=pgsql